Module3 task1
htmlacademy-adaptive/2006935-cat-energy-25 pull request #4
Opened 2022-04-15 11:21 UTC by Stuloviv

2022-04-18 06:36 UTC, Dima-Dim requested changes
С разбиенем стилей на файлы вроде нормально, а вот с переисползованием кода не очень. Смысл БЭМ а не в том что всё разбить на части, а в том, чтобы выделить одинаковые блоки и элементы, чтобы их можно было переиспользовать, иначе нет ни удобства, ни оптимизации, ни взаимодействия одинаковых частей проекта. Возможно, стоит пересмотреть лайв и материалы про БЭМ, чтобы лучше понять суть этой методологии. Внимательней посмотреть демонстрации учебного проекта.

2022-04-18 06:36 UTC, Dima-Dim commented on source/less/blocks/catalog/main-title-catalog.less
> +.main-title-catalog {
Очень похоже на `advantages__title`.

2022-04-18 06:36 UTC, Dima-Dim commented on source/less/blocks/catalog/products-additional.less
> +.products-additional__title {
Тоже очень похоже на `advantages__title`.

2022-04-18 06:36 UTC, Dima-Dim commented on source/less/blocks/catalog/products-main.less
> +.products-main__list {
Какой-то очень общий набор стилей для списка.

2022-04-18 07:01 UTC, Stuloviv commented
Привет! Суть БЭМ понимаю. Просто засела мысль, что немного позже всё оптимизировать.)) Сейчас сделаю.)

2022-04-19 06:50 UTC, Dima-Dim requested changes
Группировать файлы блоков по дополнительным папкам в таком виде как это сделал ты не корректно. Это противоречит логике БЭМ. Любой блок может быть использован в любом месте проекта. Разделять блоки так, ты ментально сужаешь область их использования. И эта же причина приводит к появлению дублирующегося кода. Выделять нужно действительно уникальные блоки для проекта, которые могут быть переиспользованы в любом месте проекта, а не блоки для каталога или футера. Скорее всего именно поэтому у тебя уже на старте так много блоков и по количеству, и по желанию разбить из на папки.

2022-04-19 06:50 UTC, Dima-Dim commented on source/catalog.html
> +          <button class="main-product__button button button--more">Показать все</button>
Элемент `main-product__button` вне блока `main-product` - проверять тут https://yoksel.github.io/html-tree/

2022-04-22 17:12 UTC, Dima-Dim reviewed
Правку вноси в следующем задании.

2022-04-22 17:12 UTC, Dima-Dim commented on source/less/blocks/programs.less
> +.programs-card {
А вто это уже другой блок.

2022-04-22 17:12 UTC, merged